parameters:
#    devster_project.example.class: Devster\ProjectBundle\Example

services:
#    devster_project.example:
#        class: %devster_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
