devster_employee_list:
    path:     /employees
    defaults: { _controller: DevsterAppBundle:Employee:index }
    methods: [GET]
devster_employee_view:
    path: /employees/{id}
    defaults: { _controller: DevsterAppBundle:Employee:view }
    methods: [GET]
devster_employee_put:
    path: /employees/{id}
    defaults: { _controller: DevsterAppBundle:Employee:put }
    methods: [PUT]

devster_employee_post:
    path: /employees
    defaults: { _controller: DevsterAppBundle:Employee:post }
    methods: [POST]

devster_employee_edit:
    path: /employees/{id}/edit
    defaults: { _controller: DevsterAppBundle:Employee:edit }
    methods: [GET]

devster_employee_create:
    path: /employees/{id}/new
    defaults: { _controller: DevsterAppBundle:Employee:create }
    methods: [GET]
devster_employee_delete:
    path: /employees/{id}/delete
    defaults: { _controller: DevsterAppBundle:Employee:delete }
    methods: [DELETE]
