parameters:
    devster_employee.employee.service.class: Devster\AppBundle\Service\EmployeeService
    devster_employee.employee.entity.class: Devster\AppBundle\Entity\Employee

services:
    devster_employee.employee.service:
        class: %devster_employee.employee.service.class%
        arguments: [@doctrine.orm.entity_manager, "%devster_employee.employee.entity.class%"]
