devster_app:
    resource: "@DevsterAppBundle/Resources/config/routing.yml"
    prefix:   /api
    type: rest

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /