# .travis.yml
language: php

php:
    - 5.5

before_script:
  - curl -s http://getcomposer.org/installer | php
  - COMPOSER_ROOT_VERSION=dev-master php composer.phar --dev install
  - build/travis.sh

script: phpunit -c build/

notifications:
  email: "santiago.diaz@me.com"
